bundles: []
database: postgres
models:
  contributor:
    name: Contributor
    namepascalcase: Contributor
    namelowercase: contributor
    hasdate: false
    hascustomtypes: true
    fields:
    - type: string
      name: Name
      isslice: false
      slicetype: ""
    - type: uint
      name: Total
      isslice: false
      slicetype: ""
    - type: Repository
      name: Repository
      isslice: false
      slicetype: ""
    - type: string
      name: ImageLink
      isslice: false
      slicetype: ""
    - type: string
      name: ImageLink
      isslice: false
      slicetype: ""
    - type: uint64
      name: RepositoryID
      isslice: false
      slicetype: ""
  repository:
    fields:
    - isslice: false
      name: Name
      slicetype: ""
      type: string
    - isslice: false
      name: Author
      slicetype: ""
      type: string
    - isslice: false
      name: Base64
      slicetype: ""
      type: string
    hascustomtypes: false
    hasdate: false
    name: repository
    namelowercase: repository
    namepascalcase: Repository
  week:
    fields:
    - isslice: false
      name: Name
      slicetype: ""
      type: string
    - isslice: false
      name: Total
      slicetype: ""
      type: uint
    - isslice: false
      name: RepositoryID
      slicetype: ""
      type: uint64
    - isslice: false
      name: Repository
      slicetype: ""
      type: Repository
    hascustomtypes: true
    hasdate: false
    name: Week
    namelowercase: week
    namepascalcase: Week
package: github.com/edwinvautier/gh-readme-contrib
use_docker: true
