bundles: []
database: postgres
models:
  repository:
    fields:
    - isslice: false
      name: Name
      slicetype: ""
      type: string
    - isslice: false
      name: Author
      slicetype: ""
      type: string
    - isslice: false
      name: Base64
      slicetype: ""
      type: string
    hascustomtypes: false
    hasdate: false
    name: repository
    namelowercase: repository
    namepascalcase: Repository
  week:
    name: Week
    namepascalcase: Week
    namelowercase: week
    hasdate: false
    hascustomtypes: true
    fields:
    - type: string
      name: Name
      isslice: false
      slicetype: ""
    - type: uint
      name: Total
      isslice: false
      slicetype: ""
    - type: uint64
      name: RepositoryID
      isslice: false
      slicetype: ""
    - type: Repository
      name: Repository
      isslice: false
      slicetype: ""
package: github.com/edwinvautier/gh-readme-contrib
use_docker: true
